#!/usr/bin/env python3
"""
Extract symbol addresses from the ROM's linker .map or .sym file
and generate a Lua memory_map module for mGBA integration tests.

Usage:
    python3 extract_symbols.py pokefirered_coop.map \
        --symbols gPlayerPosition,gGhostNpcState,gMultiplayerState \
        --output test/lua/memory_map.lua
"""

import argparse
import re
import sys
from pathlib import Path

# Symbols we always want, mapped to their Lua ADDR key names
DEFAULT_SYMBOLS = {
    # Player state
    "gSaveBlock1Ptr":       "SAVE_BLOCK_1",
    "gObjectEvents":        "OBJECT_EVENTS",

    # Multiplayer module (these are defined in src/multiplayer.c)
    "gMultiplayerState":    "MP_STATE",
    "gGhostNpcState":       "GHOST_STATE",
    "gMultiplayerFlags":    "MP_FLAGS",
    "gRandomizerSeed":      "MP_SEED",

    # Flags
    "gSaveBlock1":          "SAVE_BLOCK_1_DIRECT",
}

# Struct field offsets (manually maintained, update if structs change)
STRUCT_OFFSETS = """
-- Struct field offsets (update these if struct definitions change)
-- See include/multiplayer.h for struct layouts
OFFSET = {
    -- MultiplayerState
    MP_CONNECTED     = 0x00,  -- u8: 1 if connected
    MP_ROLE          = 0x01,  -- u8: 0=host, 1=guest
    MP_PARTNER_MAP   = 0x02,  -- u16: partner's map ID
    MP_PARTNER_X     = 0x04,  -- u16: partner's X position
    MP_PARTNER_Y     = 0x06,  -- u16: partner's Y position
    MP_PARTNER_FACE  = 0x08,  -- u8: partner's facing direction
    MP_BOSS_READY    = 0x09,  -- u8: boss readiness flags
    MP_SEED_VALUE    = 0x0C,  -- u32: randomizer seed

    -- GhostNpcState
    GHOST_ACTIVE     = 0x00,  -- u8: 1 if ghost NPC is spawned
    GHOST_OBJ_ID     = 0x01,  -- u8: object event ID
    GHOST_MAP_ID     = 0x02,  -- u16: map ghost is on
    GHOST_X          = 0x04,  -- u16: ghost X
    GHOST_Y          = 0x06,  -- u16: ghost Y
    GHOST_FACING     = 0x08,  -- u8: ghost facing direction
}
"""


def parse_sym_file(path: Path) -> dict[str, int]:
    """Parse a .sym file (format: ADDRESS LABEL)"""
    symbols = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith(("#", ";")):
                continue
            match = re.match(r"([0-9a-fA-F]{8})\s+(\S+)", line)
            if match:
                addr = int(match.group(1), 16)
                name = match.group(2)
                symbols[name] = addr
    return symbols


def parse_map_file(path: Path) -> dict[str, int]:
    """Parse a GNU ld .map file for symbol addresses"""
    symbols = {}
    with open(path) as f:
        for line in f:
            # Match lines like: 0x02000000   gSaveBlock1
            match = re.match(r"\s*(0x[0-9a-fA-F]+)\s+(\w+)", line)
            if match:
                addr = int(match.group(1), 16)
                name = match.group(2)
                symbols[name] = addr
    return symbols


def generate_lua(symbols: dict[str, int], requested: dict[str, str]) -> str:
    """Generate the Lua memory_map.lua content"""
    lines = [
        "-- AUTO-GENERATED by extract_symbols.py",
        "-- Do not edit manually. Re-run after rebuilding the ROM.",
        "",
        "ADDR = {"
    ]

    found = 0
    missing = []

    for c_name, lua_name in sorted(requested.items(), key=lambda x: x[1]):
        if c_name in symbols:
            lines.append(f"    {lua_name:24s} = 0x{symbols[c_name]:08X},")
            found += 1
        else:
            lines.append(f"    -- {lua_name:24s} MISSING ({c_name} not found in map)")
            missing.append(c_name)

    lines.append("}")
    lines.append("")
    lines.append(STRUCT_OFFSETS)
    lines.append("")

    # Helper functions
    lines.append("""
-- Helper: read a flag by ID from the save block
function isFlagSet(flagId)
    -- Flags are stored as a bitfield in SaveBlock1
    -- The offset of the flags array within SaveBlock1 depends on the game
    -- For FireRed, find the offset by checking the struct definition
    local FLAGS_OFFSET = 0x0EE0  -- placeholder, verify from SaveBlock1 struct
    local baseAddr = ADDR.SAVE_BLOCK_1_DIRECT
    if baseAddr == nil then
        error("SAVE_BLOCK_1_DIRECT not found in memory map")
    end
    local byteIndex = math.floor(flagId / 8)
    local bitIndex = flagId % 8
    local byte = emu:read8(baseAddr + FLAGS_OFFSET + byteIndex)
    return (byte & (1 << bitIndex)) ~= 0
end

-- Helper: read multiplayer state field
function readMPState(fieldOffset)
    return emu:read8(ADDR.MP_STATE + fieldOffset)
end

function readMPState16(fieldOffset)
    return emu:read16(ADDR.MP_STATE + fieldOffset)
end

function readMPState32(fieldOffset)
    return emu:read32(ADDR.MP_STATE + fieldOffset)
end

-- Helper: read ghost NPC state field
function readGhostState(fieldOffset)
    return emu:read8(ADDR.GHOST_STATE + fieldOffset)
end

function readGhostState16(fieldOffset)
    return emu:read16(ADDR.GHOST_STATE + fieldOffset)
end
""")

    # Summary
    lines.append(f"-- Found {found}/{len(requested)} symbols")
    if missing:
        lines.append(f"-- Missing: {', '.join(missing)}")
        lines.append("-- These may not exist yet if the multiplayer module hasn't been added.")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Extract ROM symbols for Lua tests")
    parser.add_argument("mapfile", help="Path to .map or .sym file")
    parser.add_argument("--symbols", help="Comma-separated extra symbols (C_NAME:LUA_NAME)")
    parser.add_argument("--output", default="test/lua/memory_map.lua", help="Output Lua file")
    args = parser.parse_args()

    path = Path(args.mapfile)
    if not path.exists():
        print(f"Error: {path} not found", file=sys.stderr)
        sys.exit(1)

    # Parse based on extension
    if path.suffix == ".sym":
        all_symbols = parse_sym_file(path)
    else:
        all_symbols = parse_map_file(path)

    print(f"Parsed {len(all_symbols)} symbols from {path}")

    # Build requested symbol map
    requested = dict(DEFAULT_SYMBOLS)
    if args.symbols:
        for entry in args.symbols.split(","):
            if ":" in entry:
                c_name, lua_name = entry.split(":", 1)
            else:
                c_name = entry
                lua_name = entry.upper()
            requested[c_name] = lua_name

    # Generate output
    lua_code = generate_lua(all_symbols, requested)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(lua_code)
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
