/** Shared session info created on Host or loaded on Join. */
export interface SessionInfo {
  /** Unique identifier for this save file pair, stored in .coop sidecar. */
  sessionId: string;
  /** Path to the .sav file. */
  savePath: string;
  /** Path to the .coop sidecar file. */
  coopPath: string;
  /** 6-character alphanumeric room code (upper case). */
  roomCode: string;
  /** Whether this client is the host. */
  isHost: boolean;
  /** Encounter seed generated by the host (0 until received from server). */
  encounterSeed: number;
  /** Whether encounter randomization is enabled. */
  randomizeEncounters: boolean;
}

export type ConnectionStatus =
  | "disconnected"
  | "connecting"
  | "connected"
  | "reconnecting"
  | "error";
