-- AUTO-GENERATED by tools/extract_symbols.py — do not edit by hand.
-- Regenerate with: python3 tools/extract_symbols.py pokefirered.map test/lua/memory_map.lua

local M = {}

M.Task_HandleYesNoInput = 0x081FC830
M.gCoopSettings = 0x030015B8
M.gDisableTextPrinters = 0x02037478
M.gMpAddrTable = 0x030015C4
M.gMpBlockExchange = 0x0203137C
M.gMpRecvRing = 0x02031480
M.gMpSendRing = 0x02031584
M.gMultiplayerState = 0x0300157C
M.gPlayerParty = 0x0203234C
M.gSaveBlock1Ptr = 0x03005330
M.gSaveBlock2Ptr = 0x0300532C
M.gSaveblock1 = 0x0200FF94
M.gStringVar4 = 0x02036D88
M.gTasks = 0x03006D94
M.sFirstTextPrinter = 0x02037470
M.sGlobalScriptContextStatus = 0x03001831
M.sLockFieldControls = 0x03001830

return M
