-- AUTO-GENERATED by tools/extract_symbols.py — do not edit by hand.
-- Regenerate with: python3 tools/extract_symbols.py pokefirered.map test/lua/memory_map.lua

local M = {}

M.gCoopSettings = 0x0300158C
M.gMpRecvRing = 0x02031350
M.gMpSendRing = 0x02031454
M.gMultiplayerState = 0x0300157C
M.gSaveBlock1Ptr = 0x030052E8

return M
