-- test_boss_readiness.lua
-- Integration tests for the boss readiness protocol.
-- Requires two mGBA instances connected via link cable (Phase 6, Tauri app).
-- Run with mGBA's built-in Lua scripting console on each instance.
--
-- DEFERRED: These tests require live two-player connectivity.
-- They document the expected behavior for manual verification and future automation.

-- Load the memory map generated by tools/extract_symbols.py
local mm = require("memory_map")

local function readU8(addr)  return emu:read8(addr)   end
local function readU16(addr) return emu:read16(addr)  end

local function getMultiplayerState()
    local base = mm.gMultiplayerState
    return {
        connState       = readU8(base + 0),
        bossReadyBossId = readU8(base + 4),
        partnerBossId   = readU8(base + 5),
    }
end

local function getSendRingAvailable()
    local base = mm.gMpSendRing
    local head = readU8(base + 2)
    local tail = readU8(base + 3)
    return (tail - head) & 0xFF
end

-- ============================================================
-- TEST: Both players interact with Brock → battle starts
-- ============================================================
-- Setup: Two connected instances both have player walk up to Brock.
-- Expected outcome:
--   1. Instance A sends BOSS_READY(id=1) → send ring has 2 bytes (type + id)
--   2. Instance B sends BOSS_READY(id=1) → same
--   3. Relay server sends BOSS_START back to both
--   4. waitbossstart unblocks on both instances
--   5. Brock battle begins on both screens
--
-- Manual check: after interacting with Brock on both screens,
-- both should see the Brock intro cutscene (not the "Waiting" message).

print("[DEFERRED] TestBothPlayersReadyBossBattle: requires live session")

-- ============================================================
-- TEST: One player cancels → other remains in waiting state
-- ============================================================
-- Setup: Player A interacts with Brock (waiting), Player B walks away.
-- Expected outcome:
--   1. Player A is stuck on "Waiting for partner..." message
--   2. Player B sends BOSS_CANCEL → Player A's partnerBossId clears to 0
--   3. Player A's waitbossstart continues polling (no start)
--   4. If Player A also walks away, their bossReadyBossId clears
--
-- Manual verification (single instance, simulated cancel):
local state = getMultiplayerState()
print(string.format("[INFO] bossReadyBossId=%d partnerBossId=%d",
    state.bossReadyBossId, state.partnerBossId))
print("[DEFERRED] TestOneCancelRemainWaiting: requires live session")

-- ============================================================
-- TEST: Badge flags propagate after gym defeat
-- ============================================================
-- After beating Brock on instance A:
--   1. FLAG_DEFEATED_BROCK (0x4B0) should be set on both instances via FLAG_SET sync
--   2. FLAG_BADGE01_GET (0x867) should be set on both instances via FLAG_SET sync
--   3. Route 3 gate (checks FLAG_BADGE01_GET) should open on both screens
--
-- Memory check: read flags byte 268 on both instances after Brock is defeated
local FLAG_BADGE01_BYTE = 268  -- 0x867 / 8
local FLAG_BADGE01_BIT  = 7    -- 0x867 & 7
-- (run this after defeating Brock)
-- local flagsByte = readU8(mm.gSaveBlock1 + 0x1270 + FLAG_BADGE01_BYTE)
-- assert(flagsByte & (1 << FLAG_BADGE01_BIT) ~= 0, "BADGE01_GET should be set")
print("[DEFERRED] TestBadgeFlagPropagates: requires live session + post-battle state")

print("Boss readiness Lua stubs loaded. Live tests deferred to Phase 6.")
