#!/usr/bin/env python3
"""
extract_symbols.py — parse the linker .map file and emit test/lua/memory_map.lua

Usage:
    python3 tools/extract_symbols.py pokefirered.map test/lua/memory_map.lua

The script extracts any symbol whose name matches the patterns listed in
WANTED_PATTERNS and writes a Lua table so mGBA Lua test scripts can look
up symbol addresses without hard-coding them.

Symbol line format in the map file:
    <whitespace> 0xHEXADDR <whitespace> SYMBOL_NAME
"""

import re
import sys
from pathlib import Path

# Symbols to include in the output table.
# Each entry is a regex; any symbol name that matches is included.
WANTED_PATTERNS = [
    r"^gMultiplayerState$",
    r"^gMpSendRing$",
    r"^gMpRecvRing$",
    r"^gCoopSettings$",
    # Phase 3+: flag/var globals will be added here when implemented.
    # r"^gSaveBlock1Ptr$",
]

_WANTED_RE = [re.compile(p) for p in WANTED_PATTERNS]

# Linker map symbol line: leading whitespace, hex address, whitespace, name.
_MAP_LINE_RE = re.compile(r"^\s+(0x[0-9a-fA-F]{8,16})\s+(\w+)\s*$")


def wanted(name: str) -> bool:
    return any(rx.match(name) for rx in _WANTED_RE)


def parse_map(path: Path) -> dict[str, int]:
    symbols: dict[str, int] = {}
    with open(path, "r", errors="replace") as f:
        for line in f:
            m = _MAP_LINE_RE.match(line)
            if m:
                addr_str, name = m.group(1), m.group(2)
                if wanted(name):
                    symbols[name] = int(addr_str, 16)
    return symbols


def emit_lua(symbols: dict[str, int], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- AUTO-GENERATED by tools/extract_symbols.py — do not edit by hand.",
        "-- Regenerate with: python3 tools/extract_symbols.py pokefirered.map test/lua/memory_map.lua",
        "",
        "local M = {}",
        "",
    ]
    for name in sorted(symbols):
        lines.append(f'M.{name} = 0x{symbols[name]:08X}')
    lines += ["", "return M", ""]
    out_path.write_text("\n".join(lines))


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <map-file> <output.lua>", file=sys.stderr)
        return 1

    map_path = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    if not map_path.exists():
        print(f"Error: map file not found: {map_path}", file=sys.stderr)
        return 1

    symbols = parse_map(map_path)

    if not symbols:
        print("Warning: no matching symbols found in map file.", file=sys.stderr)

    emit_lua(symbols, out_path)

    print(f"Wrote {len(symbols)} symbol(s) to {out_path}:")
    for name, addr in sorted(symbols.items()):
        print(f"  {name} = 0x{addr:08X}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
